### DISCUSSION TITLE
My shiki Dark/Light Dual themes not work, what should I do ?

### DISCUSSION THREAD

**Discussion by nibazshab** [vuepress/ecosystem#133] [Q&A] [answered]
I have configured the following according to [https://shiki.style/guide/dual-themes](https://shiki.style/guide/dual-themes)

```ts
    shikiPlugin({
      langs: [
        // 'LANGS',
      ],
      themes: {
        light: 'github-light',
        dark:'github-dark-dimmed'
      },
    },)
```

Still, can only show the light theme.

![image](https://github.com/vuepress/core/assets/44338441/d973601c-7245-49f4-8845-e55758ffade0)
![image](https://github.com/vuepress/core/assets/44338441/15278a92-3ed2-472a-a178-4fe425644531)

- `index.scss`

```scss
div[class*='language-']::before {
  display: none;
}

:root {
  --c-brand: #087ea4;
  --c-brand-light: #066583;

  --c-bg-light: #f6f8fa;
  --c-text-lighter: #ff4c0f;

  --code-bg-color: #eff1f3;
  --code-hl-bg-color: rgba(0, 0, 0, 0.07);
  --code-ln-color: #c1c1c1;
}

html.dark {
  --code-bg-color: #282c34;
  --code-hl-bg-color: rgba(0, 0, 0, 0.66);
  --code-ln-color: #9e9e9e;
}
```
