### ISSUE TITLE
[Feature request] Dynamically color change of the level-2 headings border

### ISSUE THREAD

**Issue by onedonedone** [vuepress/ecosystem#190]
### Description

Level-2 headings border flashs when changing colors since the transition time is not consistent with the background.

https://github.com/vuepress/ecosystem/assets/168573322/2e0e61cd-1066-42ac-a4be-8ed33221bcd4

### Suggested solution

Since the transition style of `body` and `code` elements are set in `src/client/styles/normalize.scss`, I think it might be proper to add here.

```scss
// normalize.scss
...
h2 {
  border-color: var(--c-border);
  transition: border-color var(--t-color);
}
...
```
